version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  django:
    container_name: django-prj
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -c gunicorn.conf.py
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
    depends_on:
      - postgres